use_frameworks!

platform :ios, '8.0'

target 'KYVoiceConvert_Example' do
  pod 'KYVoiceConvert', :path => '../'

  target 'KYVoiceConvert_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
